---
m3_version: 1.0.beta2
profile:
  date_modified: '2024-06-01'
  responsibility: https://samvera.org
  responsibility_statement: Hyrax Initial Profile
  type:
  version: 1
classes:
  Hyrax::Work:
    display_label: Work
  Hyrax::AdministrativeSet:
    diplay_label: AdministrativeSet
  Hyrax::PcdmCollection:
    display_label: PcdmCollection
  Hyrax::FileSet:
    display_label: FileSet
contexts:
  flexible_context:
    display_label: Flexible Metadata Example
mappings:
  blacklight:
    name: Additional Blacklight Solr Mappings
  metatags:
    name: Metatags
  mods_oai_pmh:
    name: MODS OAI PMH
  qualified_dc_pmh:
    name: Qualified DC OAI PMH
  simple_dc_pmh:
    name: Simple DC OAI PMH
properties:
  title:
    available_on:
      class:
      - Hyrax::AdministrativeSet
      - Hyrax::FileSet
      - Hyrax::PcdmCollection
      - Hyrax::Work
    cardinality:
      minimum: 1
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    definition:
      default: Enter a standardized title for display. If only one
        title is needed, transcribe the title from the source
        itself.
    display_label:
      default: Title
    index_documentation: displayable, searchable
    indexing:
    - 'title_sim'
    - 'title_tesim'
    form:
      required: true
      primary: true
      multi_value: true
    mappings:
      metatags: twitter:title, og:title
      mods_oai_pmh: mods:titleInfo/mods:title
      qualified_dc_pmh: dcterms:title
      simple_dc_pmh: dc:title
    property_uri: http://purl.org/dc/terms/title
    range: http://www.w3.org/2001/XMLSchema#string
    requirement: required
    sample_values:
    - Pencil drawn portrait study of woman
  date_modified:
    available_on:
      class:
      - Hyrax::AdministrativeSet
      - Hyrax::FileSet
      - Hyrax::PcdmCollection
      - Hyrax::Work
    cardinality:
      minimum: 0
      maximum: 1
    multi_value: false
    display_label:
      default: Date Modified
    property_uri: http://purl.org/dc/terms/modified
    range: http://www.w3.org/2001/XMLSchema#dateTime
    sample_values:
    - "2024-06-06 21:06:51 +0000"
  date_uploaded:
    available_on:
      class:
      - Hyrax::AdministrativeSet
      - Hyrax::FileSet
      - Hyrax::PcdmCollection
      - Hyrax::Work
    cardinality:
      minimum: 0
      maximum: 1
    multi_value: false
    display_label:
      default: Date Uploaded
    property_uri: http://purl.org/dc/terms/dateSubmitted
    range: http://www.w3.org/2001/XMLSchema#dateTime
    sample_values:
    - "2024-06-06 21:06:51 +0000"
  depositor:
    available_on:
      class:
      - Hyrax::AdministrativeSet
      - Hyrax::FileSet
      - Hyrax::PcdmCollection
      - Hyrax::Work
    cardinality:
      minimum: 0
      maximum: 1
    multi_value: false
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Depositor
    index_documentation: searchable
    indexing:
    - 'depositor_tesim'
    property_uri: http://id.loc.gov/vocabulary/relators/dpt
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Julie Allinson
  creator:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 1
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Creator
    index_documentation: displayable, searchable
    indexing:
    - 'creator_sim'
    - 'creator_tesim'
    form:
      required: true
      primary: true
    property_uri: http://purl.org/dc/elements/1.1/creator
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Julie Allinson
  license:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: License
    index_documentation: searchable
    indexing:
    - 'license_tesim'
    form:
      required: false
      primary: true
    property_uri: http://purl.org/dc/terms/license
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - http://creativecommons.org/licenses/by/3.0/us/
  abstract:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Abstract
    index_documentation: searchable
    indexing:
    - 'abstract_tesim'
    property_uri: http://purl.org/dc/terms/abstract
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - This is an abstract.
  based_near:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Location
    index_documentation: displayable, searchable
    indexing:
    - 'based_near_sim'
    - 'based_near_tesim'
    form:
      primary: false
    property_uri: http://xmlns.com/foaf/0.1/based_near
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - San Diego, California, United States
  contributor:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Contributor
    index_documentation: searchable
    indexing:
    - 'contributor_tesim'
    form:
      primary: false
    property_uri: http://purl.org/dc/elements/1.1/contributor
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Julie Allinson
  date_created:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#dateTime
      sources:
      - 'null'
    display_label:
      default: Date Created
    index_documentation: searchable
    indexing:
    - 'date_created_tesim'
    form:
      primary: false
    property_uri: http://purl.org/dc/terms/created
    range: http://www.w3.org/2001/XMLSchema#dateTime
    sample_values:
    - "2024-06-06 21:06:51 +0000"
  description:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Description
    index_documentation: searchable
    indexing:
    - 'description_tesim'
    form:
      primary: false
    property_uri: http://purl.org/dc/elements/1.1/description
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - This is a description.
  identifier:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Identifier
    index_documentation: searchable
    indexing:
    - 'identifier_tesim'
    form:
      primary: false
    property_uri: http://purl.org/dc/terms/identifier
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - abc123
  keyword:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Keyword
    index_documentation: displayable, searchable
    indexing:
    - 'keyword_sim'
    - 'keyword_tesim'
    form:
      primary: false
    property_uri: http://schema.org/keywords
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Metadata
    - Repository
  label:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
      maximum: 1
    multi_value: false
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Label
    property_uri: info:fedora/fedora-system:def/model#downloadFilename
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - file_label.txt
  language:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Language
    indexing:
    - 'language_tesim'
    index_documentation: searchable
    form:
      primary: false
    property_uri: http://purl.org/dc/elements/1.1/language
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - English
    - Spanish
  publisher:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Publisher
    indexing:
    - 'publisher_tesim'
    index_documentation: searchable
    form:
      primary: false
    property_uri: http://purl.org/dc/elements/1.1/publisher
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Scholastic
  related_url:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Related URL
    index_documentation: searchable
    indexing:
    - 'related_url_tesim'
    form:
      primary: false
    property_uri: http://www.w3.org/2000/01/rdf-schema#seeAlso
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - http://example.com/resource1
  relative_path:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
      maximum: 1
    multi_value: false
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Relative Path
    property_uri: http://scholarsphere.psu.edu/ns#relativePath
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - /path/to/resource
  resource_type:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Resource Type
    index_documentation: displayable, searchable
    indexing:
    - 'resource_type_sim'
    - 'resource_type_tesim'
    property_uri: http://purl.org/dc/terms/type
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Article
    - Conference Proceeding
  rights_notes:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Rights Notes
    indexing:
    - 'rights_notes_tesim'
    index_documentation: searchable
    property_uri: http://purl.org/dc/elements/1.1/rights
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Creative Commons license.
  rights_statement:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Rights Statement
    index_documentation: searchable
    indexing:
    - 'rights_statement_tesim'
    property_uri: http://www.europeana.eu/schemas/edm/rights
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - http://rightsstatements.org/vocab/InC/1.0/
  source:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Source
    index_documentation: searchable
    indexing:
    - 'source_tesim'
    property_uri: http://purl.org/dc/terms/source
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Original Manuscript
    - Digital Archive
  subject:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Subject
    index_documentation: displayable, searchable
    indexing:
    - 'subject_sim'
    - 'subject_tesim'
    form:
      primary: false
    property_uri: http://purl.org/dc/elements/1.1/subject
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Art
    - Science
